import React, { useEffect, useState } from 'react'
import { createRoot } from 'react-dom/client'
import Markdown from 'react-markdown'
import { Bookmark, Check, ChevronLeft, ChevronRight, ExternalLink, FileText, Layers, Newspaper, Search, Scale, ArrowUpRight, Moon, Sun } from 'lucide-react'
import { Button } from '@/components/ui/button'
import { Card, CardContent } from '@/components/ui/card'
import { Input } from '@/components/ui/input'
import { Tabs, TabsList, TabsTrigger } from '@/components/ui/tabs'
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select'
import { Sheet, SheetContent, SheetHeader, SheetTitle } from '@/components/ui/sheet'
import { Skeleton } from '@/components/ui/skeleton'
import { Sidebar, SidebarContent, SidebarHeader, SidebarInset, SidebarMenu, SidebarMenuButton, SidebarMenuItem, SidebarProvider, SidebarTrigger, useSidebar } from '@/components/ui/sidebar'
import { useAPI, type Article, type Review, type Source } from '@/lib/api'
import { LegacyPanel } from '@/components/legacy-panel'
import { Recommendations, ReviewMetrics, Laws, Content, type Candidate } from '@/components/restored-features'
import './index.css'

type Scrap = {key: string; kind: string; title: string; text: string; url?: string; source?: string; published?: string; sources?: Source[]}
declare global { interface Window { PreviewTheme: {apply(theme:string,root:HTMLElement,storage?:Storage):string}; ResearchStore: {createStore(storage: Storage): {read(): {scraps: Scrap[]}; saveScrap(value: Scrap): unknown; addTask(value: Candidate): unknown}} } }
const menu = [{id:'briefing', title:'브리핑', icon:Layers}, {id:'explore',title:'기사 탐색',icon:Newspaper}, {id:'laws',title:'법령·규제',icon:Scale}, {id:'saved',title:'보관함',icon:Bookmark}]
const safeURL = (value?: string) => { try { const u = new URL(value || ''); return /^https?:$/.test(u.protocol) ? u.href : undefined } catch { return undefined } }
function Text({children}: {children?: string}) { return <div className="reading"><Markdown components={{a: ({href, children}) => <a href={safeURL(href)} target="_blank" rel="noopener noreferrer">{children}</a>}}>{(children || '').replace(/^·\s*/gm,'- ')}</Markdown></div> }
function Loading({error, retry}: {error?: string; retry(): void}) { return error ? <div role="alert" className="empty"><p>{error}</p><Button variant="outline" onClick={retry}>다시 불러오기</Button></div> : <div aria-label="불러오는 중" aria-busy="true" className="space-y-5"><Skeleton className="h-12 w-2/3"/><Skeleton className="h-40 w-full"/><Skeleton className="h-72 w-full"/></div> }
function Picker({value,onChange,options,label}: {value: string; onChange(v:string):void; options:{value:string;label:string}[];label:string}) { return <Select value={value} onValueChange={onChange}><SelectTrigger aria-label={label}><SelectValue placeholder={label}/></SelectTrigger><SelectContent>{options.map(o => <SelectItem key={o.value} value={o.value}>{o.label}</SelectItem>)}</SelectContent></Select> }
function Navigation({page}: {page:string}) { const {setOpenMobile} = useSidebar(); return <Sidebar variant="inset"><SidebarHeader><a className="brand" href="#briefing"><span className="brand-mark"><Layers size={19}/></span>SAB Trend</a></SidebarHeader><SidebarContent className="px-3 pt-6"><SidebarMenu>{menu.map(m => <SidebarMenuItem key={m.id}><SidebarMenuButton asChild isActive={page===m.id} className="h-11 px-3 text-[15px]"><a href={'#'+m.id} onClick={() => setOpenMobile(false)}><m.icon/><span>{m.title}</span></a></SidebarMenuButton></SidebarMenuItem>)}</SidebarMenu></SidebarContent></Sidebar> }
function Sources({sources}: {sources: Source[]}) { return sources.length ? <details className="sources"><summary>근거 기사 <span>{sources.length}</span></summary><div>{sources.map(s => <a key={s.id} href={safeURL(s.url)} target="_blank" rel="noopener noreferrer"><span>{s.title}</span><ArrowUpRight size={16}/></a>)}</div></details> : null }
function Briefing({save, saved, open,addTask}: {save(s:Scrap):void; saved:Set<string>; open(id:number):void;addTask(t:Candidate):boolean}) {
  const initial=location.hash.slice(1).split('/')[1]||'weekly'
  const [kind,setKind] = useState(initial.startsWith('monthly')?'monthly':'weekly'), [period,setPeriod] = useState(initial.split(':')[1]||'current'),[view,setView]=useState('review')
  useEffect(()=>{const sync=()=>{const value=location.hash.slice(1).split('/')[1]||'weekly';setKind(value.startsWith('monthly')?'monthly':'weekly');setPeriod(value.split(':')[1]||'current')};window.addEventListener('hashchange',sync);return()=>window.removeEventListener('hashchange',sync)},[])
  const periods = useAPI<{periods:{period:string;label:string}[]}>('/api/reviews/periods?kind='+kind)
  const review = useAPI<Review>('/api/reviews?kind='+kind+(period==='current'?'':'&period='+encodeURIComponent(period)))
  const data = review.data, editorial = data?.editorial
  const options = [{value:'current',label:kind==='weekly'?'이번 주':'이번 달'}, ...(periods.data?.periods || []).map(p => ({value:p.period,label:p.label}))]
  return <><div className="page-heading"><h1>브리핑</h1><div className="toolbar"><Tabs value={kind} onValueChange={v=>{setKind(v);setPeriod('current');history.replaceState(null,'','#briefing/'+v)}}><TabsList><TabsTrigger value="weekly">주간</TabsTrigger><TabsTrigger value="monthly">월간</TabsTrigger></TabsList></Tabs><Picker label="리뷰 기간" value={period} onChange={v=>{setPeriod(v);history.replaceState(null,'','#briefing/'+kind+(v==='current'?'':':'+v))}} options={options}/></div></div>
    <div className="feature-tabs"><Button variant={view==='review'?'default':'outline'} onClick={()=>setView('review')}>리뷰</Button><Button variant={view==='recommend'?'default':'outline'} onClick={()=>setView('recommend')}>사업 추천</Button>{data&&kind==='monthly'&&<><Button asChild variant="outline"><a href={'/report?month='+encodeURIComponent(data.period)} target="_blank" rel="noopener noreferrer">월간보고서<ExternalLink/></a></Button><Button asChild variant="outline"><a href={'/report.md?month='+encodeURIComponent(data.period)}>Markdown</a></Button></>}</div>
    {!data ? <Loading error={review.error} retry={review.retry}/> : <>
      {view==='recommend'?<Recommendations period={data.period} editorialTasks={editorial?.tasks} sources={editorial?.sources||[]} addTask={addTask}/>:<>
      <div className="review-heading"><span className="date-label">{data.label}</span><h2>{editorial?.title || '리뷰'}</h2>{editorial && <Button variant="outline" onClick={()=>save({key:'review:'+data.period,kind:'review',title:editorial.title,text:[editorial.summary,...editorial.sections.map(s=>'## '+s.title+'\n'+s.body)].join('\n\n'),sources:editorial.sources})}>{saved.has('review:'+data.period)?<Check/>:<Bookmark/>}{saved.has('review:'+data.period)?'저장됨':'리뷰 저장'}</Button>}</div>
      {editorial ? <><Card className="summary-card"><CardContent><Text>{editorial.summary}</Text></CardContent></Card><div className="review-grid">{editorial.sections.map((s,i)=><Card key={s.title}><CardContent><div className="section-heading"><span>{String(i+1).padStart(2,'0')}</span><h3>{s.title.replace(/^\d+[.)]\s*/, '')}</h3></div><Text>{s.body}</Text><Sources sources={(editorial.sources||[]).filter(source=>s.source_ids.includes(source.id))}/></CardContent></Card>)}</div></> : <p className="empty">등록된 리뷰가 없습니다.</p>}
      <ReviewMetrics data={data}/>
      <section className="article-section"><div className="section-bar"><h2>주요 기사</h2><a href={'#explore/articles?'+new URLSearchParams({since:data.start||'',until:data.through||''})}>전체 보기 <ArrowUpRight size={16}/></a></div><ArticleList items={(data.articles||[]).slice(0,10)} open={open}/></section></>}
    </>}
  </>
}
function ArticleList({items,open}: {items:Article[];open(id:number):void}) { return <div className="article-list">{items.map(item=><button className="article-row" key={item.id} onClick={()=>open(item.id)}><div className="article-copy"><h3>{item.title}</h3>{item.summary && <p>{item.summary}</p>}<div className="article-meta"><span>{item.source || new URL(safeURL(item.url)||'https://unknown.local').hostname}</span><time>{item.published?.slice(0,10)}</time></div></div><ArrowUpRight size={18}/></button>)}</div> }
function Detail({id,save,saved,open}: {id:number;save(s:Scrap):void;saved:Set<string>;open(id:number):void}) { const result=useAPI<Article>('/api/item/'+id); const item=result.data; return item?<><SheetHeader><div className="article-meta"><span>{item.source}</span><time>{item.published?.slice(0,10)}</time></div><SheetTitle className="detail-title">{item.title}</SheetTitle></SheetHeader><div className="detail-body"><div className="toolbar"><Button onClick={()=>save({key:'article:'+item.id,kind:'article',title:item.title,text:item.insight||item.summary||'',url:item.url,source:item.source,published:item.published})}>{saved.has('article:'+id)?<Check/>:<Bookmark/>}{saved.has('article:'+id)?'저장됨':'저장'}</Button>{safeURL(item.url) && <Button variant="outline" asChild><a href={safeURL(item.url)} target="_blank" rel="noopener noreferrer">원문<ExternalLink/></a></Button>}</div><h3 className="feature-title">AI 요약</h3>{item.insight?<Content text={item.insight}/>:<p>등록된 AI 요약이 없습니다.</p>}{!!item.checklist?.length&&<div className="law-applications"><h3>업무 적용점</h3>{item.checklist.map(c=><Content key={c.label+c.detail} text={'- **'+c.label+'**: '+c.detail}/>)}</div>}{item.summary&&<details className="sources"><summary>기사·제개정 내용</summary><Content text={item.summary}/></details>}{!!item.related?.length&&<section className="article-section"><h3 className="feature-title">관련 기사</h3><ArticleList items={item.related} open={open}/></section>}</div></>:<div className="p-8"><SheetTitle className="sr-only">기사 상세</SheetTitle><Loading error={result.error} retry={result.retry}/></div> }
function App() {
  const route=()=>{const id=location.hash.slice(1).split(/[/?]/)[0];return menu.some(m=>m.id===id)?id:'briefing'}
  const [,refreshRoute]=useState(0)
  const [theme,setTheme]=useState(document.documentElement.classList.contains('dark')?'dark':'light')
  const [page,setPage]=useState(route),[detail,setDetail]=useState<number|null>(null),[scraps,setScraps]=useState<Scrap[]>([]),[notice,setNotice]=useState(''),[selected,setSelected]=useState<Scrap|null>(null)
  useEffect(()=>{const update=()=>{setPage(route());refreshRoute(n=>n+1);setDetail(null);setSelected(null);window.scrollTo(0,0)};window.addEventListener('hashchange',update);return()=>window.removeEventListener('hashchange',update)},[])
  useEffect(()=>{const sync=()=>{try{setScraps(window.ResearchStore.createStore(localStorage).read().scraps)}catch{setNotice('보관함을 불러오지 못했습니다.')}};sync();window.addEventListener('storage',sync);return()=>window.removeEventListener('storage',sync)} ,[])
  const save=(scrap:Scrap)=>{try{const store=window.ResearchStore.createStore(localStorage);store.saveScrap(scrap);setScraps(store.read().scraps);setNotice('저장했습니다.')}catch{setNotice('저장하지 못했습니다. 브라우저 저장 공간을 확인해 주세요.')}}
  useEffect(()=>{if(!notice)return;const timer=setTimeout(()=>setNotice(''),4000);return()=>clearTimeout(timer)},[notice])
  const addTask=(task:Candidate)=>{try{window.ResearchStore.createStore(localStorage).addTask(task);setNotice('검토 보드에 추가했습니다.');return true}catch{setNotice('저장하지 못했습니다.');return false}}
  const toggleTheme=()=>{const next=theme==='dark'?'light':'dark';window.PreviewTheme.apply(next,document.documentElement,localStorage);setTheme(next)}
  const legacyRoute=(hash:string)=>{const mapped=hash.replace(/^#workspace/,'#saved').replace(/^#reg/,'#laws');const destination=mapped.slice(1).split(/[/?]/)[0];if(menu.some(m=>m.id===destination)){if(destination===page)history.replaceState(null,'',mapped);else location.hash=mapped}}
  const saved=new Set(scraps.map(s=>s.key))
  return <SidebarProvider style={{'--sidebar-width':'15rem'} as React.CSSProperties}><Navigation page={page}/><SidebarInset><header className="site-header"><SidebarTrigger aria-label="메뉴 열기/닫기"/><span className="header-divider"/><span>{menu.find(m=>m.id===page)?.title}</span><Button className="theme-toggle" variant="ghost" size="icon" aria-label={theme==='dark'?'라이트 모드로 전환':'다크 모드로 전환'} title={theme==='dark'?'라이트 모드':'다크 모드'} onClick={toggleTheme}>{theme==='dark'?<Sun/>:<Moon/>}</Button></header><main id="main-content" className="main-content">
    {page==='briefing'?<Briefing save={save} saved={saved} open={setDetail} addTask={addTask}/>:page==='explore'?<><div className="page-heading"><h1>기사 탐색</h1><Button variant="outline" asChild><a href="#explore/start">주제 발견</a></Button></div><LegacyPanel autoHeight theme={theme} route={location.hash.startsWith('#explore/')?location.hash.slice(1):'explore/articles'} title="기사·흐름·연관 네트워크" onRoute={legacyRoute} onOpenItem={setDetail}/></>:page==='laws'?<Laws open={setDetail}/>:<><div className="page-heading"><h1>보관함</h1></div><LegacyPanel theme={theme} route={location.hash.replace(/^#saved/,'workspace')||'workspace/scraps'} title="보관함·메모·과제 검토" onRoute={legacyRoute} onOpenItem={setDetail}/></>}
  </main></SidebarInset><Sheet open={detail!==null||selected!==null} onOpenChange={open=>{if(!open){setDetail(null);setSelected(null)}}}><SheetContent aria-describedby={undefined} className="detail-sheet">{detail!==null?<Detail id={detail} save={save} saved={saved} open={setDetail}/>:selected?<><SheetHeader><SheetTitle className="detail-title">{selected.title}</SheetTitle></SheetHeader><div className="detail-body"><Text>{selected.text}</Text><Sources sources={selected.sources||[]}/></div></>:null}</SheetContent></Sheet>{notice&&<div role="status" className="notice">{notice}</div>}</SidebarProvider>
}
createRoot(document.getElementById('root')!).render(<React.StrictMode><App/></React.StrictMode>)
